apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAecfoQGsdxjTXvzg5dSI7mnSlSqDWTdjBAMtSDVll32sTEWqXclu6Nr4rjZipBwF+VVHzVHCS2rtZ6H5QHm3gJbPteq0rhNJ3nGZOcaxW5bLP5mwT5+9Ux3wJkr2c4+7wplvxMuLcvnOlvbb49sQrGG2xBjbUInar295dqFzmIq4/ZjTbOaiB/7D5lKCJDEPxGJWE9K35AJg5XinVA8AKaTIaLNmqIY3PCvxgAntahLGnT/LjuDRUu2fXKjKd7TnwL1ahQ7OMdYrFs+V7twXJJ2CFAu+WQFqZJ7PwSvl/+2b7RJxwZox32RRVAVFCYFRO7Z3NHwrSSpdJCX/IhCv9bhWDOgFJj0XUnKAyru4F9E4IQUdaEVWukkhuj7DfjXbKnHYggT2ooP38CkRh1F5mhwJtJbaDOr18SXUEb0ar5Ayx2f/LOSYg2/mcPF+Ar8O0wke5aRIlFgZzx3yxZRoMQ9ViQQgmC0YORwp4ACZzfbk8m98aK198PUIHYkd+1bUPUxggbB1t9le84CUAOG3lq1GWqSsj+mcC/7mpvOJ7LHtWaghvlqMcW0fzifKbDav+rxwQB/dHm2U0vEIPG+lh44/oyefDKBDbck4CpZNFjlVCL+at5jDETaOkRU8so/N1lspmN0j+DLmVAc0xnqUZTnS9+nc4G4aQCYbm10WNG1LjYF5L22OtjEOoYRsMgD9xT4Q1hb61/3RJ+EJZ8WjMqK42kSSCaDKtIryx7HchIQSVYqJqGDwkWyogmLRktQ64hpdYLaBmL+jmYRIQcV1bbUOMJRS0qnrdD6hhHNDNpj+mximmrXdSxWovu7fc/t4UuM7THvhXsjOOzkAnZQUoM/rzDqfeDww3x6yJ6dq1yorU8mH5yCZsHvgd0XXfavofTB8E=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

