apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBRrXyDGpdgyt7siC/UU+SYKOFJrF/cB2qQwYk3PVl6OCZoXEGviOvgoSgQGOv3PFyhPj4AiENifDbq1OOdoX//bqVkthRz7BgNLKp7B6u1O/9st4wZG1xKcv4QnZ7dtsDyyZqGMhE/5rqfHXX/8UCBMQ+tjgEHZ8rgXtohyeBzOJoMNGM/UNNpMTTIEtDYmC2irZKvwvEc7d5jl8W7PrhO4khtdPmtg9J9hUx9c+b4I26ZT59rkNX1cl9t0JkcfKdz79PR66Thl+TynVmdTpfz6kra9KIFujFiYv/9IiWbyGP/y84GxHI2RGuosnPdbvODbOOqOYowvPDo6W/WFIDiM8zL+GytMwkuKTbQqM99vG1lJZZyoZK7XoGLDQVsXKmQ4fmLgKA/0mGIi+XjhnQ7vmKohTvgBVJvWH5i3SPPg+0uLy0oEDlyv2YaAnUP3SOG3hiEvyAGkQ/gujQLzLQ7fRCrsZFGRxdaxEwyidDzCnCOzzITsz2Rd8z7ja4aqXiOMf70sxy5F6/aHd6ZBARjE7L7GoIguG8YP7iSjaVMBtceCiDslQswBOBhqzBYWZQsW5NR/zmrMSZEEODUwomHBlAJuAazobHULqJdn4bnRbfRJbV2toQkkOU6eAe81a1RWtyJF415PlY74NrchqnrrFMHynKo4LNF7sYu0uPX30KbWV3AnUMdjwc4FOqYa4QuS1zmD5+aADOKUwpw9nKhP5+tNXiN36z+FbDh41vf4nrnB7rn1tFDY7hKQf6HLFEWIDhrKiuIBmFqUsbLH2TsKeAMfP4mMVLLg5rlPduRNSYBuU+ILwLrt+SIepIUQaZffvIAnqRwWX5J90Ch9H1Buk7xqIerews0i53BCVznDjiqsOtHCFv/PdeBMbnZhu3VgRQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

