apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAOTKpgMx9e9wS8bAGMSKwzqgqusl0DHvfGh/l0/H1b7VeZyZHdl+z/6I9FLEZxDWYNZKCvP/roQrQ5pn3FZ4l5oWkw35Vcd55TDtpCThJ+yh0PyeADnXeLgV4w0H+w9hn0K11ESAJgMyRF1vUPcgJ8e7/ImouT98E8jHDqnTISDeUPP5ku+vgCLEts4dfIBNEcN6SMKgRwu7eVq3stj1wpKg2JX69WF1KaMiyqLOrtrTN6N3yeyEYT0EK0K3YWfnWPgCACTgXju+hjXSxn5RWu3oUvHio5Me/61bwWQL5xTSZ5oB5shR/YZhy/EsrrkkTfrgKfROmPCPUjkZwT2vkj/QcFyJ8PkVcHLga+JzgtMLORMcOUOfnLHWyBK7UWPSZmQOiSgIxYZ3WqP8GW7fNLtLgowCkVgOSbcLh6l8iLT1prdILyO47YVbPV0KH/lI6b0ou85kj4IHYQGep/MSZWOuyyZwi71QPC44cTuoGFAMxJf9K/XHg+layCHzH7jFogqoFO8t22C+S5JOfdj5Sxwv4x3cvssAJHlwGonE8QzOurtZ7CGnmNrNSLc66EfdWnb5DvN/0zPUbp5s3F/TvHUIKNp0pIrcbe8KbfQj8PYFUX2BlEFUQsaF633WvMw4YEg1c2PSq+utCWIjKbgZYdKR2Z1hZP125U54Vc1vIOQslEoLhAzCiimkd26S2iFkkMuBQ/5f2GcN6HYUeM2LmnP7lJ0FNnWQx27Ywm8HW1+Z36C0ooZ2kiVUjdYNBIUnZOD1B0r6gJo09Y0C8G9G40Y61WKVqEo4Lw/PyipTZAQnNOi+deGGOi03K+ovZwG7oKkEfymsQBhXYJvlUDMHSD89qSm5MCH5q+yKjiuk8Vrd/jRHMRcngQI7HBoWmKIo/OfTE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

