apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCXaE6ib4yfP4c31cZsPWi7RcWW8IWUUAnZ8Byn9HVA+wIN52a5YbIPIlUTZx0qwn6GtdAoNoetnD8N8vrHW0qkBeWtcY+c2Qb+XuNN4s04LzFcqB4eTrvekZLJlyhBiPJ1SK2EpoiLEimQrarwyJohsl4lpHoRPwBGEZOT9hOn6OMItrYP0A9vadSzlYT/O8fUb7H+lCKMHRvhElLCdmEaKb9v/2LI/B396Nut5vo8FqqlfrmITWlmVGp1yfAA8Fn/aBWf+/miRH9PVtss/SB/uHA9sT4CHbdt7zYpO5DKAZ7cSgWmF8y9j3S2fA/P/99jdc0QdWPa7jeog3WKwnRULjrLwb6fxUqJlvNKTIU4FxD3NQT77LjN87vmxy0BygrQyVg4zHhaaeegdeBOQ1t4YaxTXM7gHThII5cP+YS8Ku9RdLahxTWxtCIbOmmgK7UFMkiRhWENGpCCVSmKNXSSqiAopfr4gaSudCTw1TvpI/JqQjHmCYZKrQXmxdNx8RGO4IhIfWJNcthQIeLfJVCMnTTxjMrZabqYdtOdA6mrVfnXz9Dim+nE8RWyWx2h11zE00e8o8BfQf8aMIlagnDS5JHreZcJdH6/XGsK96g/bIfqXJw1biBW04atjuHSW5ygreJ1dFLZDzACeCBBCLXjxPNkwj+DNvHRNdoWn0qyacZ+r3+qD3YWhdfzp4+zwSuUl0Enkj2iW+i0GPV49E70K9BgvoErSl/GeFezo4KxvVIalTVGNtgO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

