apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCXRfaHoOTnpeCKQ5GoY7p7f/p0BQgEsE6sR6w6447eDFNj+KDMHAbTjFPKD/k9trtqeC5ckZ4llcA555A6VAskf3EmuX6aEuE39DaYZo9nriXZ6JWeFg4S00ta+HC+japzeaQO1qBN7M5ce/MCu8ZjJnnQ+/UNg9vmrDvtNdTutTQhgfaFf1S4ckslZ2vJmGmCEZtLJk8kiK3x6qvwFO5okk9x20uoEkot0dCBaRPGB3C9gDSCRQN23WrWg4B+qRQ/BtnEtKZ/mrQhm8NQh4zdATi7Q6S+aiwJAZ7exnpVBzxO2jNdOb+KHSN+mS/HEiT3IxeahQjWvZqbYwzJXy/ZNMDddWGg+7qT/tY1DUSL81dRWJNbFAbnKxQ4IGGxeHyowqCM/rbHStxUxEh1d6yI3BMbIWu+UkyTN/Efid3RLz3vKORxTZclPGTu2N5wzjd2KkWfbGWjIV729Yfu45ulYc+DPzDPPp1rvVWHCwCc6O3/BMudqWBIEES0Rnq1hXwbEGoHDuKV47BowbofwBlmv4rohRrsCDU1REUiRBW4Lw9Qco0nkvqooUqX3QCxMgh9Jjv4Ib4ON13e6aKZF/K+LWfQ+dtIX2jExOOA0zeMlBIpBaNkXB2XfIXg6icvqOUyapDc4hgeeBb9BE17JPfc7J1rZOwjpqqrGlwQhH0aIceUd+Hk0UjPI486aL3RSu7FJLGIh955BV9/rdGay9Yy3w4M/FTnZfc/jCTU5HHRLZIqdH6Rjq0t
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

