apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCoo7DisRRGxEI6EgaueO6JFEiRhvvW9yTMFWTtL3U/wBMOtBcVj9SG6nKta+iblY27VbI/wlpVGrQVQh6bmy724VxB3Zh26gePxPnvryZpNYdiYVKI0WyTUCQ/3vmqkdhiK0QWrr6wq/aLfnQ4gS1F2cT4QNT1vSCW6Ee8KTHFF9l9qOhSu5ahOtWyVJwFe9MNQ/0yi+qZRR2VO3H2GWKLUFghleD3pRYf5ZlwH11T0eukfNd42QW2xoI8QKJxSVyMXmDFWS1VPPu/r7kGV2AHman9yBItc24YxQ1+dofzYE7kWV/VwTXGH9/UndCdLt9Pya3W7WhMg42a9YRlJM0xGT8alpWqczmc2rwq/+I/Cm6xd/f/oTqoh65CccfUwFpaHsMIKkrnNKotDbwD6HorB8GYDFoiS8krmKpbXQCrsIFxGp1xBrHHt75/cDyYh+63hzD8kzA3ETzI6RzsfiYyu3X9KRwSmcCUpb/nGjFB6nr2qA9sOnExuhHDMWa727yVrabTp5CrnEZ4tghU0i3vLXGymPQ5sJJQMj3deRQ8Z+3N1FTBo+Si+Ux1lYzit5z1upqERu3SurXYusrksa4Uo6m3pmDMH73mCE2/S7QP3jV2jWO698Vzr2I2mtKYR2RszYBAQB63picmoNI1WaJu+4LEjnfnEdZPyKsOvPWozmnfJ1XmgKpzbETX0TjdyM88aHL54KfH7/nCGz2qBw9jWDx9BGxRW/v4HeUm5N7Y0xQ+i0eDg4tE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

